export const GET_SCHEDULE_START = 'GET_SCHEDULE_START'
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS'
export const GET_SCHEDULE_ERROR = 'GET_SCHEDULE_ERROR'

export const RENT_INTERVAL_START = 'RENT_INTERVAL_START'
export const RENT_INTERVAL_SUCCESS = 'RENT_INTERVAL_SUCCESS'
export const RENT_INTERVAL_ERROR = 'RENT_INTERVAL_ERROR'

